### ISSUE TITLE
Implementera kvarvarande MEDUSA steg i StaG

### ISSUE THREAD

**Issue by lis4matilda** [boulund/stag-mwc#1]
# Implementera bowtie mapping, counting, combining, annotating

### Medusa scripts:
* `streamAligner.py`
* `combineCounts.py`
* `annotateCounts.py`

### input needed:
* filtered.humanremove.reads
* database index
* database annotation tsv file

## Plan
* Starta med bowtie (Vi kanske kan implementera fler mappers senare). 
   * Parat eller inte parat, det är frågan...
* Ge database index som input
* Ett folder-system per database (Ge folder samt filer namn som sätts i config-filen)
* Starta med den counting som finns i Medusa idag (lägg andra count-möjligheter som options)
* Statistics (maybe we can start with what is used in MEDUSA but if you want to adjust, please adjust.)
* Combine samples into one file (features som rader, prov som kolumner). Jag har skrivit hjälpskript till detta steget om ni vill kika. 
* Summera statistik baserat på prov.
* Annotate. Collaps feature into the same annotation given in the annotation file. 
   * input: columns to use for annotation (eg. 1,4,5). 
   * Output: 1 combined countfile per annotation.  

Filsystemet kommer bli (typ):
```
MEDUSA_databasnamn (folder)
       Counts (folder)
             counts
             counts.log
       Combine (folder)
            combine.feature
            combine.anno1
            combine.anno4
            combine.anno5
       summary.stats.all.samples
```

**Comment by boulund** [comment]
@lis4matilda, jag formaterade ditt inlägg lite så det blir lättare att se. Github stöder Markdown annotering av poster, så det är enkelt att göra simpel formatering av text för att göra det tydligt att läsa. Hoppas jag fick formateringen rätt ungefär som du hade tänkt :).

Detta är en lite detalj, men jag funderar på om vi inte ska ha en output struktur för MEDUSA-grejerna som ser ut typ så här:

```
output_dir/
    MEDUSA/
        <db_name>/
            Counts/
                <sample>.counts.tab
                <sample>.counts.log
            Combine/
                combine.feature
                combine.anno1
                combine.anno2
                ... osv...
        summary.stats.all.samples
```

Det blir nog lite enklare att ha en undermapp för varje databas man kört till MEDUSA, så ligger alla MEDUSA-output samlade i en mapp i den samlade outputmappen för hela workflowet. 

Jag utgår ifrån att de MEDUSA-script som du nämner inte ändrats nämnvärt sen publikationen? Bifogar dem till det här inlägget för snabb access (men de hamnar nog förr eller senare i själva workflowet i någon form):

[combineCounts.py.txt](https://github.com/boulund/stag-mwc/files/1880275/combineCounts.py.txt)
[streamAligner.py.txt](https://github.com/boulund/stag-mwc/files/1880276/streamAligner.py.txt)
[annotateCounts.py.txt](https://github.com/boulund/stag-mwc/files/1880277/annotateCounts.py.txt)

Gissningsvis kommer vi implementera bowtie2-mappningssteget utan `streamAligner.py`, för att hela det ramverket som finns där helt enkelt inte behövs när vi har Snakemake som ram runt hela vårt workflow. Sen kommer vi hugga relevanta delar ur `combineCounts.py` or `annotateCounts.py`.

**Comment by lis4matilda** [comment]
Det är helt ok :)
Vi behöver inte kalla det Medusa alls. Kan bara inte komma på vad vi skall kalla det. 
Tänker att vi inte behöver implementera scripten alls, tror snakemake är bättre, bara att ha som referens om det behövs. 

Lisa

**Comment by lis4matilda** [comment]
Hm, inte helt hundra på hur du menar, pileup när någon form av coverage om jag inte minns fel. Det viktigaste vi måste bestämma är hur vi assignar reads (best match, unique mapps, equal distribution). Tony tyckte vi kunde implementera alla, tror best match är implementerat i medusa nu. Sedan antar jag att det är som att mäta coverage per feature.

**Comment by boulund** [comment]
Jepp, du minns rätt: pileup från samtools beräknar coverage. `pileup.sh` från BBMap räknar ut mer än bara coverage. Den räknar coverage per referenssekvens, så om ni har komplicerade referensdatabaser med flera annoterade regioner per referenssekvens är det nog inte riktigt rätt verktyg. Det är sjukt smidigt i alla fall, och jag rekommenderar det starkt över samtools om du inte har nån annan preferens (eller nåt annat downstream-steg som absolut behöver output från samtools).

Det går redan nu att justera best match/unique mappings osv för bowtie2-mappningen med bowtie2:s egna inbyggda settings för det (bara att lägga till alla extra bowtie2-settings man vill ha med i en setting som heter "extra" i `config.yaml`)

**Comment by boulund** [comment]
Det är helt upp till dig hur du vill göra med alla outputfiler från stegen. Givetvis kommer det ta en massa plats med en massa intermediära filer. Snakemake har inbyggda funktioner för att automatiskt ta bort intermediära filer när de inte längre behövs om man markerar dem som `temp`. Då håller Snakemake koll på om en fil fortfarande behövs av en downstreamprocess i workflowet, t.ex. en fastq med trimmade reads innan human-filtrering som man kanske inte behöver spara för all framtid (de går ju snabbt att göra om från rådatan om man verkligen behöver den), men den behövs ju fram tills man filtrerat bort human-DNA. När workflowet som helhet börjar bli mer komplett kan vi lätt se över vilka filer som faktiskt behöver sparas och vilka som kan raderas och justera det allt eftersom. 

Jag tror du har helt rätt i att det är mycket effektivare att mappa mot en mindre databas med specifika features om man vill ha bara de reads som mappar till ett subset av feature-sekvenser. De flesta mappers kan väl mappa mot en referensdatabas och automatiskt producera en ny FASTQ-fil med bara de reads som mappade enligt matchningskriteria (BBMap gör det iaf).

**Comment by boulund** [comment]
Jag funderar på att splitta upp denna issue i ett par mindre bitar under "MEDUSA in Stag-mwc" milestonen. Denna kan få ligga kvar som en generell issue för allmän diskussion tills vidare.
