### ISSUE TITLE
Produce count files from bowtie2 output

### ISSUE THREAD

**Issue by boulund** [boulund/stag-mwc#4]
@lis4matilda suggested we start off with the counting that was used in MEDUSA. The count files could e.g. be put in a separate `Counts` folder inside the bowtie2 mapping results folder, inside a folder named after the database used to map against: 

```
output_dir/
    bowtie2/
        <db_name>/
            Counts/
                <sample>.counts.tab
```

Commit bdd980d9c269a24e405da42d057033d9b153a58f added a rule to use BBMap's `pileup.sh` to produce two output files from the bowtie2 mapping output bam file: `<sample>.covstats.txt` and `<sample>.rpkm.txt`. The two files contain the following information:

### covstats
The `covstats` output from BBMap (in this case `pileup.sh`) contains the following columns:
```
ID                  Name of reference sequence
Avg_fold            Average fold coverage across reference sequence
Length              Length of reference sequence
Ref_GC              GC content of reference sequence
Covered_percent     Percent of reference sequence covered by reads
Covered_bases       Number of bases of reference sequence covered by reads
Plus_reads          Number of reads mapping in plus orientation
Minus_reads         Number of reads mapping in minus orientation
Read_GC             GC content of mapped reads
Median_fold         Median fold coverage
Std_dev             Standard deviation
```

### rpkm
The `rpkm` output from BBMap (in this case `pileup.sh`) contains the following information on the first four lines:
* The name of the input file (i.e. the bowtie2 mapping output bam file)
* The total number of reads
* The number of mapped reads
* The number of reference sequences in the database

It then contains the following columns:
```
Name      Name of reference sequence
Length    Length of reference sequence
Bases     Number of bases in reference sequence
Coverage  Coverage of reference sequence
Reads     Number of reads that mapped to reference sequence
RPKM      Reads per kilobase million 
Frags     Number of fragments mapped to reference sequence
FPKM      Fragments per kilobase million
```

I think this information is pretty much what you want @lis4matilda, but is there anything else output by MEDUSA that this doesn't cover? 

It is fairly trivial to merge reads counts per sample or whatever you want to combine into the final combined output files.

**Comment by boulund** [comment]
I recently merged #10, which implemented exactly what I describe above. We can wait to close this issue until you have had a change to have a look at the output @lis4matilda.

**Comment by boulund** [comment]
I just spoke to @lis4matilda and decided to implement also a step that summarizes read counts per annotation of the reference sequences, at any user-defined level supported by the annotation that is available. I will assess this using the annotation files available for IGC that we've used previously with MEDUSA.

**Comment by boulund** [comment]
Perhaps we should consider using [featureCounts](http://bioinf.wehi.edu.au/featureCounts/) for the gene annotation count summation. It is fairly straightforward to whip up a somewhat generally applicable count summation tool that we could use in StaG-mwc, but sometimes it makes sense to go with an established tool. 

From to their [announcement post] on the SeqAnswers forum:
```
(1) It carries out precise and accurate read assignments by taking care of indels, junctions and fusions in the reads.
(2) It takes less than 4 minutes to summarize 20 million pairs of reads to 26k RefSeq genes using one thread, and only uses 40MB of memory (you can run it on a Mac laptop).
(3) It supports multi-threaded running, making it extremely fast for summarizing large datasets.
(4) It supports GTF format annotation and SAM/BAM read data. 
(5) It supports strand-specific read summarization.
(6) It can perform read summarization at both feature level (eg. exons) and meta-feature level (eg. genes).
(7) It allows users to specify whether reads overlapping with more than one feature should be counted or not.
(8) It gives users full control on the summarization of paired-end reads, including allowing them to check if both ends are mapped and/or if the paired-end distances satisfy the distance criteria.
(9) It discriminates the features, which were overlapped by both ends from the same fragment, from those which were overlapped by only one end so as to get more fragments counted.
(10) It allows users to specify whether chimeric fragments should be counted.
```
Those are some nice features, and I think it would make sense to use this instead of a custom solution that is most likely going to be less flexible. A custom solution would also be less validated, and would require more investigation for other users interested in our methods; it would be unknown to other researchers when publishing. 

The main drawback I see is that featureCounts requires sam/bam input, which would be slightly more space consuming than the fairly barebones read count tables that we already have. It also requires a different form of input for the annotations than what we currently use, which could be frustrating in the beginning.

**Comment by lis4matilda** [comment]
Fast...det som det verktyget verkar göra är ju att assigna counts till features, det måste ju göras från bam/sam-filer och måste göras innan vi får count-filer. 

Annotera count-filer är ju bara att summera counts från olika features för samma annotering. Eller missar jag något?

**Comment by boulund** [comment]
Ok, I've played around with the IGC_medusa annotation now, and it's really straightforward to convert that annotation to something that `featureCounts` can use (GTF format). I've added a script, `convert_IGC_annotation.py`, that can convert the default IGC annotations, as well as annotation in a two-column format (like what's used in `CombinedNRGenesReduced.KEGG.txt`), to GTF format for use with `featureCounts`. It works very well when I tested it on a subset of all annotations. However, I've encountered some issues when summarizing read counts per feature using the whole file. I think the reason is a poor implementation of string concatenation in `featureCounts` and I intend to submit a bug report. So, currently it is not possible to run the featureCounts-step on the output of Bowtie2 or BBMap mapping. 

As it is right now, I have added a branch called `featureCounts` that adds the option of using featureCounts to produce read count summaries per sample for any annotated feature in a GTF file. The GTF file must of course contain annotations for all features of interest in the reference file used when mapping with Bowtie2/BBMap.  I don't think it's a wasted effort, as I can see myself using this quite a lot, but considering the current version doesn't work very well with the admittedly massive IGC_medusa annotations, we should probably still consider an alternative (custom) solution (for the IGC_medusa annotation).

**Comment by boulund** [comment]
I wrote a custom script, `make_count_table.py`, that merges counts per annotation using a simple two-column tab-separated annotation file for a reference database. It is fairly quick and should handle databases of any size as long as you have enough memory. Except a memory usage of about 4x the text file size of your annotations file.

This should satisfy your MEDUSA-needs from StaG-mwc @lis4matilda. Give it a spin!

**Comment by lis4matilda** [comment]
🎉, for sure I will!

**Comment by boulund** [comment]
I just merged a fairly substantial first draft of the documentation, I hope it helps you to get started (see https://stag-mwc.readthedocs.org). Before you can run on UPPMAX, we need to create a cluster configuration file that sets good defaults for CPU and time allocations for all Slurm jobs. I've created an issue about this: #29
